# this is used for letting you know that you need to update/change your config file
version: 5

# the locale to use for messages
# all messages can be customised but this allows you to
# choose messages that are already translated
# locales can be found in the locale/ folder
locale: en

# interval (in minutes) to check to autorankup players
# ranking up manually wil always be enabled
# set to 0 to disable
autorankup-interval: 0

# whether /ranks and /prestiges should be enabled (true) or disabled (false)
# /rankup3 reload will not do anything if this is changed,
# you will have to restart your server.
ranks: true
# you can alternatively negate the permission rankup.prestiges
# this will also make the command not autocomplete in 1.13
prestiges: true

# whether or not /prestige and /prestiges should be enabled.
# when a player reaches the top rank, they can do /prestige to return to the first rank,
# but you will be able to grant them an additional "prestige" group or additional items.
#
# if you do not want this command to autocomplete, make sure
# you negate the permission rankup.prestige with your permissions plugin.
# if enabled, a prestiges.yml file will be generated with some example prestiges
# You must restart your server when you change this for it to work!
prestige: false

# if true, players with the permission rankup.notify will receive notifications when they join
# to update if they are on an older version of Rankup.
notify-update: true

# how people should confirm ranking up
# options are: gui, text or none
confirmation-type: 'gui'

# how long, in seconds, people have to wait between a successful /rankup or /prestige
# set to 0 to disable.
cooldown: 1

# if enabled, players can run /maxrankup to rankup as many times as possible,
# before they fail the requirements for the next rank.
# the permission rankup.maxrankup is used for this command, but it is usually given by default.
# note that /maxrankup, if enabled, has no confirmation.
max-rankup:
  # You must restart your server if you enable or disable /maxrankup!
  enabled: false
  # whether to send a message for each rankup a player does
  # if set to true, the chat may be spammed for each rankup a player goes through with /maxrankup
  # if set to false, only the last rankup will be shown (if a player starts on rank A, then does
  # /maxrankup and ranks up to B and then C, it will just say "player has ranked up to C")
  individual-messages: true

gui:
  rows: 1
  rankup:
    material: EMERALD_BLOCK
    # index can be separated by spaces to show in multiple groups
    # for example: 0-3 9-12 18-21
    # you can also just use a single number instead of a range.
    index: 0-3
    name: '&a&lConfirm'
    # lore is optional
    lore: '&6Rankup to &b{RANK}'
  cancel:
    material: REDSTONE_BLOCK
    index: 5-8
    name: '&c&lCancel'
  fill:
    name: ' '
    # if you are using a 1.8-1.12 and you want to change this
    # you can use MATERIAL:data, for example STAINED_GLASS_PANE:8
    # this works for both the rankup and cancel blocks as well
    material: BLACK_STAINED_GLASS_PANE

# options when using the text rankup confirmation
text:
  # the time in seconds for a player to
  # confirm by typing /rankup again
  timeout: 10

# placeholders:
# https://github.com/okx-code/Rankup3/wiki/PAPI-Placeholders
placeholders:
  # format for money. for more information, see
  # https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html
  money-format: "#,##0.##"
  percent-format: "0.##"
  # the format used for requirements
  simple-format: "#.##"
  # used for current_rank and next_rank placeholders when a player is not in anything in rankups.yml
  not-in-ladder: "None"
  # used in the current_prestige placeholders when a player hasn't prestiged yet
  no-prestige: "None"
  # used in the next_rank and next_prestige placeholders when a player is at the highest rank or prestige
  highest-rank: "None"

# what to shorten money by.
# ie 1000 -> 1k
# set to an empty list to disable
# for each entry here, it counts as increasing by a factor of 1,000
# the first represents thousands (1,000) then millions (1,000,000) then billions (1,000,000,000) etc.
shorten:
- 'k'
- 'M'
- 'B'
- 'T'
- 'Q'
- 'Qu'
- 'S'