# This is used for letting you know that you need to update/change your config file.
# Do not change this.
version: 10

# The locale to use for messages.
# All messages can be customised but this allows you to.
# Choose messages that are already translated.
# Locales can be found in the locale/ folder.
locale: en

# Interval (in minutes) to check to autorankup players.
# Ranking up manually will always be enabled.
# Set to 0 to disable.

# Players will need the rankup.auto permission to make use of this!
# Permission is given by default.
autorankup-interval: 0

# Whether /ranks and /prestiges should be enabled (true) or disabled (false)
# /rankup3 reload will not do anything if this is changed,
# You will have to restart your server.
ranks: true

# You can alternatively negate the permission rankup.prestiges.
# This will also make the command not autocomplete in 1.13+.
prestiges: true

# Whether to enable the /ranks GUI.
# Will override the /ranks command.
ranks-gui: false

# Whether /prestige and /prestiges should be enabled.
# When a player reaches the top rank, they can /prestige to return to the first rank,
# but you will be able to grant them an additional "prestige" group or additional items.
#
# If you do not want this command to autocomplete, make sure
# you negate the permission rankup.prestige with your permissions plugin.
# If enabled, a prestiges.yml file will be generated with some example prestiges
# you must restart your server when you change this for it to work!
prestige: false

# If true, players with the permission rankup.notify will receive notifications when they join
# to update if the server is on an older version of Rankup.
notify-update: true

# +------------------------------------------------------+
# | Don't change this unless you know what you're doing! |
# +------------------------------------------------------+
# Changing this setting to "true" can lead to your rankups.yml no longer working.
#
# Learn more about this:
# https://okx.sh/rankup/Advanced-Configuration/Permission-Rankup.html
permission-rankup: false

# How people should confirm ranking up
# Options are: gui, text or none
confirmation-type: 'gui'

# How long in seconds people have to wait between a successful /rankup or /prestige
# set to 0 to disable.
cooldown: 1

# If enabled, players can run /maxrankup to rankup as many times as possible,
# before they fail the requirements for the next rank.
# The permission rankup.maxrankup is used for this command, but it is given by default.
# Note that /maxrankup, if enabled, has no confirmation.
max-rankup:
  # You must restart your server if you enable or disable /maxrankup!
  enabled: false

  # Whether to send a message for each rank a player ranks up for.
  # -> If true, the chat may be spammed for each rankup a player goes through with /maxrankup
  #      Example: a player starts on rank A, but can rankup to rank D, the chat will say:
  #        "player has ranked up to B"
  #        "player has ranked up to C"
  #        "player has ranked up to D"
  # -> If false, only the last rankup will be shown
  #      Example: a player starts on rank A, but can rankup to rank D, the chat will say:
  #        "player has ranked up to D".
  individual-messages: false

# Options when using the text rankup confirmation
text:
  # The time in seconds for a player to
  # confirm by typing /rankup again.
  timeout: 10

# Placeholders:
# https://okx.sh/rankup/Placeholders.html
placeholders:
  # Format for money. for more information, see
  # https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html
  money-format: "#,##0.##"
  percent-format: "0.##"
  # the format used for requirements
  simple-format: "#.##"
  # used for current_rank and next_rank placeholders when a player is not in anything in rankups.yml
  not-in-ladder: "None"
  # used in the current_prestige placeholders when a player hasn't prestiged yet
  no-prestige: "None"
  # used in the next_rank and next_prestige placeholders when a player is at the highest rank or prestige
  highest-rank: "None"
  # used in the %rankup_status_[rank]% placeholders
  status:
    complete: "Complete"
    current: "Current"
    incomplete: "Incomplete"
  last-rank-display-name: "last rank"

# What to shorten money by.
# ie 1000 -> 1k
# Set to an empty list to disable
# For each entry here, it counts as increasing by a factor of 1,000
# The first represents thousands (1,000) then millions (1,000,000) then billions (1,000,000,000) etc.
# This is used in the "| shortmoney" filter
shorten:
- 'K'
- 'M'
- 'B'
- 'T'
- 'Q'
- 'Qu'
- 'S'
