# this is used for letting you know that you need to update/change your config file
version: 0

# whether /ranks and /prestiges should be enabled (true) or disabled (false)
# /rankup3 reload will not do anything if this is changed,
# you will have to restart your server.
ranks: true
prestiges: true

# whether or not /prestige and /prestiges should be enabled.
prestige: true

# how people should confirm ranking up
# options are: gui, text or none
confirmation-type: 'gui'

# how long in seconds people have to wait between a /rankup and a /prestige
# only successful rankups and prestiges start the cooldown.
# set to 0 to disable.
cooldown: 1

gui:
  rows: 1
  rankup:
    material: EMERALD_BLOCK
    # index can be separated by spaces to show in multiple ways
    # ie, 0-3 9-12 18-21
    # you can also just use a single number instead of a range.
    index: 0-3
    name: '&a&lConfirm'
    # lore is optional
    lore: '&6Rankup to &b{RANK}'
  cancel:
    material: REDSTONE_BLOCK
    index: 5-8
    name: '&c&lCancel'
  fill:
    name: ' '
    # if you are using a 1.8-1.12 and you want to change this
    # you can use MATERIAL:data, for example STAINED_GLASS_PANE:8
    # this works for both the rankup and cancel blocks as well
    material: BLACK_STAINED_GLASS_PANE

text:
  # the time in seconds for a player to
  # confirm by typing /rankup again
  timeout: 10

placeholders:
  # format for money. for more information, see
  # https://docs.oracle.com/javase/8/docs/api/java/text/DecimalFormat.html
  money-format: "#,##0.##"
  percent-format: "0.##"
  # the format used for requirements
  simple-format: "#.##"
  # used for current_rank and next_rank placeholders when a player is not in anything in rankups.yml
  not-in-ladder: "None"
  # used in next_rank placeholders when there is no rankup
  highest-rank: "None"
  # used in /prestiges as the {OLD_RANK} placeholder for the first prestige rank
  first-prestige-rank: 'D'

# what to shorten money by.
# ie 1000 -> 1k
# set to an empty list to disable
shorten:
- 'k'
- 'M'
- 'B'
- 'T'
- 'Q'
- 'Qu'
- 'S'